spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  application:
    name: first-service
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        import-check:
          enabled: false
      discovery:
        enabled: true
        healthCheckPath: /my-health-check
        healthCheckInterval: 20s


server:
  port: ${APP_PORT}
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: changeit
    key-store-type: pkcs12
    key-alias: s1as


  jackson:
    serialization:
      write-dates-as-timestamps: true

space-marine:
  constraints:
    health-min-value: 0
    x-max-value: 872
    y-max-value: 110

jwt:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3SjfZDG9O2Wa7UwVrG2lFHFPr2PVAby50NhCmfstFvR8+MgimBSndRMr7eEYjkbRbT7fLVqJxH3ORunfaMJUZYeAwjKDjDMaO8Ye1SA0LCOejK0PJaHOtG7vlwv9vN1TPnEhiWZulrcfnPRI5eshf25ZEfTNUvwdlqAJ3LrKjnl66OsiZqkcujKkp+VSRO/TbEigOG/z6R+CcXr5ue0FUbawyrTy5NcYzxtKTOEpF6/572EXRbAOkOUKiJFJtmaBB4kiuw6Z2U5Cw9Ii+ntdhW45SPrBK+Eg78ag9YI+fRhJDgJnx2YyVbOSw5SXQj81uNGW5Sc0tV/+DDMbMh5T7wIDAQAB
