spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  #works for tomcat application server, not for payara
  jackson:
    serialization:
      write-dates-as-timestamps: false
  #works for tomcat application server, not for payara
server:
  servlet:
    context-path: /itmo/api
  port: 8089

jwt:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3SjfZDG9O2Wa7UwVrG2lFHFPr2PVAby50NhCmfstFvR8+MgimBSndRMr7eEYjkbRbT7fLVqJxH3ORunfaMJUZYeAwjKDjDMaO8Ye1SA0LCOejK0PJaHOtG7vlwv9vN1TPnEhiWZulrcfnPRI5eshf25ZEfTNUvwdlqAJ3LrKjnl66OsiZqkcujKkp+VSRO/TbEigOG/z6R+CcXr5ue0FUbawyrTy5NcYzxtKTOEpF6/572EXRbAOkOUKiJFJtmaBB4kiuw6Z2U5Cw9Ii+ntdhW45SPrBK+Eg78ag9YI+fRhJDgJnx2YyVbOSw5SXQj81uNGW5Sc0tV/+DDMbMh5T7wIDAQAB