jwt:
  private: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDdKN9kMb07ZZrtTBWsbaUUcU+vY9UBvLnQ2EKZ+y0W9Hz4yCKYFKd1Eyvt4RiORtFtPt8tWonEfc5G6d9owlRlh4DCMoOMMxo7xh7VIDQsI56MrQ8loc60bu+XC/283VM+cSGJZm6Wtx+c9Ejl6yF/blkR9M1S/B2WoAncusqOeXro6yJmqRy6MqSn5VJE79NsSKA4b/PpH4Jxevm57QVRtrDKtPLk1xjPG0pM4SkXr/nvYRdFsA6Q5QqIkUm2ZoEHiSK7DpnZTkLD0iL6e12FbjlI+sEr4SDvxqD1gj59GEkOAmfHZjJVs5LDlJdCPzW40ZblJzS1X/4MMxsyHlPvAgMBAAECggEAYclsOP+bJbOv1IOjQ6n5Z3gQnULdkJaTbInqrO34CmHRDiljzm23e1ceQeCY/HPIru6xPHr/Vl+wAP/w1f+y1G+dGYC/VJLV4x8fS+og13FqbdYpT+DjJjm0+0sEhukvoPjhtMCTXlWbB0mmH+8e0RsIDB37WVl7dbnOkogO/v5aCZZyuCMqFABYmkjCLtG52WNqiec55RpGTvQKUI3aENaohE3CeOO9dZAPNNTmS3maTY9YdoKjtJoCXiKRyoptaahP7r9o48oeplSMRW4J0mohoeWJhM1KhIP9D3xR1JzCS3sFeC5MUOL2skXE4LnAhRs5CW0bQ5dBTUzCjqhsxQKBgQD61cRhT7oF0vgCgoOYF6TYk6/NFQOv8ucyfmhyb4rc7Krnlq1BA+tfVoRZTAfrzCa3M1qr8dSTfxOKIRvu/9a0iau0DJjyCFL0N5QnE8hyADKEiIIb0USSAzd76plrHnuihypDbpJ7jkFHqBqAhuG1/GdaAYHr49ln9/H7YrWIXQKBgQDhtq1QNhAoxzxcDozkgsjZ+x/A+fKBr2SMENvpXqOrJIs3Fzx15DSQ19wsr3J2fYbZ0LJEPspsh8hifCq531FGARS3rO7AngUmIFPjWbdW4+YqiotahNHczAR3JCwwnP/8WwpUtHW6k4YjpEz07CuB0noTpPNlmo7DcqnAdfcYuwKBgQDxeSdDkw//GVj+eYybt29Pu+WLJcbV9J5TwtNkDzN8eS4SIsEJjO9jaZOhr4sUmgVPalXIn9dIYxZ5bGRK0eptBPfSLipzHkZVqseqUuYtsTjw08WFaBF+CzC3z2IAeGkHTt4F6oWEAq+ffxp8Tt0taB5KzJa5czDRYSWIHz+pVQKBgDnaduXeVZn+J0x5NkfD9fNZWLQ/3Ja8/Aqir5tLdKwDO+OtAwQ8r/SIP5j8h1wzpILj6S1w4rWawBPuO41U3iIRWNwTaUbZufwhwR6++i09UNuKk1lqPdhYOrTHAsSbGUn3k9hOQPbHpVQxYsBMYIJwDnZGi1R5nyodk8EO+3zNAoGBANv3ptgeEezo9IopoykVrCiso/ADN2D06LUnggYAQNXeAkScsIp9g+QKvcG3qP3BLBZGSslYbA9l/B1OZ0g6U4/A+9+jIF2pUq5tYHxb+ToKcMMEUNykPGi2Td5xF57wT4Wzg4xct7X6q1cCckmj4V05TgJleJrqRzmDx/Rlvms5
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false

server:
  port: ${AUTH_SERVICE_PORT}
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: changeit
    key-store-type: pkcs12
    key-alias: s1as
#    key-password: password
