services:
  postgres_auth_soa:
    container_name: postgres_auth_soa
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=lwbeamer
      - POSTGRES_PASSWORD=2281337
      - POSTGRES_DB=soa_auth
    volumes:
      - soa-auth-postgres-data:/var/lib/postgresql/data

  postgres_main_soa:
    container_name: postgres_main_soa
    image: postgres:15
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=lwbeamer
      - POSTGRES_PASSWORD=2281337
      - POSTGRES_DB=soa_main
    volumes:
      - soa-main-postgres-data:/var/lib/postgresql/data

volumes:
  soa-auth-postgres-data:
  soa-main-postgres-data:
